# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDir: Project2-Frontend

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: node install
  
  - script: npm install
    workingDirectory: $(workingDir)
    displayName: npm install
  
  - script: npx ng build --prod
    workingDirectory: $(workingDir)
    displayName: ng build
  
  - script: npx ng test
      --browsers ChromeHeadless
      --no-watch
      --code-coverage
    displayName: ng test
    workingDirectory: $(workingDir)
    failOnStderr: false

# requires some extra work iirc
  - script: npx ng e2e
    displayName: ng e2e
    workingDirectory: $(workingDir)
    enabled: false

  - script: npm run lint
    displayName: ng lint
    workingDirectory: $(workingDir)

  - task: SonarCloudPrepare@1
    displayName: Preparing SonarCloud
    inputs:
      SonarCloud: 'SonarCloud'
      organization: '2006-jun15-net'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '2006-jun15-net_Project2-Asher-Daniel-Jordan-Front-End'
      cliSources: '$(workingDir)/src'
      extraProperties: |
        sonar.coverage.exclusions=**/*.spec.ts,$(workingDir)/e2e/**/*
        sonar.typescript.lcov.reportPaths=$(workingDir)/coverage/$(workingDir)/lcov.info

  - task: SonarCloudAnalyze@1
    displayName: Run SonarCloud Analysis
  
  - task: SonarCloudPublish@1
    displayName: Publish SonarCloud Analysis
    inputs:
      pollingTimeoutSec: '300'
  
  - task: AzureRmWebAppDeployment@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(6bfb27c8-f9ac-40e8-9b4f-55922e406dbf)'
      appType: 'webApp'
      WebAppName: 'Project2-Hospital-Frontend'
      packageForLinux: '$(workingDir)/dist/$(workingDir)'